services:
  postgres:
    image: postgres:16-alpine
    container_name: rhm_postgres
    restart: always
    environment:
      POSTGRES_DB: gestao_documentos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rhm_app
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/gestao_documentos
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgrespassword
    volumes:
      - app_uploads:/app/uploads
    ports:
      - "8080:8080"

volumes:
  postgres_data:
  app_uploads:
