spring.application.name=gestao-documentos

spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_documentos
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
